/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EpAddLocation: typeof import('~icons/ep/add-location')['default']
    EpAim: typeof import('~icons/ep/aim')['default']
    EpAlarmClock: typeof import('~icons/ep/alarm-clock')['default']
  }
}
